FROM wubster/ubuntu-cppcms-prebuild
RUN apt-get update 
apt-get install git vim ksh -y 
#&& apt-get install -y git cmake libpcre3-dev zlib1g-dev libgcrypt11-dev libicu-dev python
WORKDIR /opt
RUN git clone https://github.com/artyom-beilis/cppcms.git cppcms
WORKDIR /opt/cppcms/build
RUN cmake ..
RUN make
RUN make install
WORKDIR /var/www
EXPOSE 8080
#CMD ["/bin/bash"]
