FROM ohrsan/base-cppcms:latest
MAINTAINER Orlando Hehl Rebelo dos Santos
ENV APP_ENV=DEV
COPY  .  /var/www
WORKDIR /var/www
RUN make app
ENTRYPOINT /var/www/launch.sh
#ENTRYPOINT [ "app", "-c", "config.js"]
EXPOSE 8080
