FROM wubster/ubuntu-cppcms-prebuild
RUN apt-get update && apt-get install lsof vim-tiny git vim ksh -y 
WORKDIR /opt
RUN git clone https://github.com/artyom-beilis/cppcms.git cppcms
WORKDIR /opt/cppcms/build
RUN cmake ..
RUN make
RUN make install
RUN rm -rf /opt/cppcms/build
WORKDIR /var/www
EXPOSE 8080
#CMD ["/bin/bash"]
