version: '2'
services:
  CppCMS-DEV-LB:
    image: rancher/lb-service-haproxy:v0.7.15
    ports:
    - 4444:4444/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
  CppCMS-DEV-SRV:
    image: ohrsan/app-cppcms
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
